In [69]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [70]:
data=pd.read_csv('sh000001.csv',index_col='date')

In [71]:
data

,open,high,low,close,volume,outstanding_share,turnover
date,,,,,,,
2010-01-04,3289.75,3295.28,3243.32,3243.76,1.094479e+10,2.924114e+09,3.742943
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340
...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588

In [72]:
data['DIF']=data['close'].ewm(span=12).mean()-data['close'].ewm(span=26).mean()

In [73]:
data['DEA']=data['DIF'].ewm(span=9).mean()

In [74]:
data['EMA200']=data['close'].ewm(span=200).mean()

In [75]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200
date,,,,,,,,,,
2010-01-04,3289.75,3295.28,3243.32,3243.76,1.094479e+10,2.924114e+09,3.742943,0.000000,0.000000,3243.760000
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932,0.861987,0.478882,3263.066050
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719,-2.279478,-0.522616,3243.007632
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340,-3.467680,-1.398706,3233.417139
...,...,...,...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002,5.492395,-0.850851,3374.647089
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083,10.480643,1.415448,3376.183039
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220,12.829492,3.698257,3377.524103
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962,14.202869,5.799179,3378.811823
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588,13.491265,7.337596,3379.883945

## 复盘金叉买、死叉卖的收益结果

In [76]:
data['DIF-DEA']=data['DIF']-data['DEA']

In [77]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,DIF-DEA
date,,,,,,,,,,,
2010-01-04,3289.75,3295.28,3243.32,3243.76,1.094479e+10,2.924114e+09,3.742943,0.000000,0.000000,3243.760000,0.000000
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932,0.861987,0.478882,3263.066050,0.383105
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,-0.146111
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719,-2.279478,-0.522616,3243.007632,-1.756862
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340,-3.467680,-1.398706,3233.417139,-2.068974
...,...,...,...,...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002,5.492395,-0.850851,3374.647089,6.343246
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083,10.480643,1.415448,3376.183039,9.065195
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220,12.829492,3.698257,3377.524103,9.131235
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962,14.202869,5.799179,3378.811823,8.403690
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588,13.491265,7.337596,3379.883945,6.153669

In [78]:
# data['div_temp']为判断金叉死叉辅助列
data['div_temp']=data['DIF-DEA']/data['DIF-DEA'].shift(1)

In [79]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,DIF-DEA,div_temp
date,,,,,,,,,,,,
2010-01-04,3289.75,3295.28,3243.32,3243.76,1.094479e+10,2.924114e+09,3.742943,0.000000,0.000000,3243.760000,0.000000,NaN
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932,0.861987,0.478882,3263.066050,0.383105,inf
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,-0.146111,-0.381386
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719,-2.279478,-0.522616,3243.007632,-1.756862,12.024163
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340,-3.467680,-1.398706,3233.417139,-2.068974,1.177653
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002,5.492395,-0.850851,3374.647089,6.343246,2.400873
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083,10.480643,1.415448,3376.183039,9.065195,1.429110
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220,12.829492,3.698257,3377.524103,9.131235,1.007285
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962,14.202869,5.799179,3378.811823,8.403690,0.920323
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588,13.491265,7.337596,3379.883945,6.153669,0.732258

In [80]:
data=data.dropna()

In [81]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,DIF-DEA,div_temp
date,,,,,,,,,,,,
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932,0.861987,0.478882,3263.066050,0.383105,inf
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,-0.146111,-0.381386
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719,-2.279478,-0.522616,3243.007632,-1.756862,12.024163
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340,-3.467680,-1.398706,3233.417139,-2.068974,1.177653
2010-01-11,3301.61,3306.75,3197.33,3212.75,1.363272e+10,2.924114e+09,4.662171,-3.400530,-1.941312,3229.885932,-1.459219,0.705286
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002,5.492395,-0.850851,3374.647089,6.343246,2.400873
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083,10.480643,1.415448,3376.183039,9.065195,1.429110
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220,12.829492,3.698257,3377.524103,9.131235,1.007285
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962,14.202869,5.799179,3378.811823,8.403690,0.920323
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588,13.491265,7.337596,3379.883945,6.153669,0.732258

In [82]:
data['res']=data.apply(lambda x: 0 if (x['div_temp'] >= 0) else (1 if (x['DIF-DEA'] > 0) else -1), axis=1)

<ipython-input-82-76ee0db85312>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['res']=data.apply(lambda x: 0 if (x['div_temp'] >= 0) else (1 if (x['DIF-DEA'] > 0) else -1), axis=1)

In [83]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,DIF-DEA,div_temp,res
date,,,,,,,,,,,,,
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932,0.861987,0.478882,3263.066050,0.383105,inf,0
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,-0.146111,-0.381386,-1
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719,-2.279478,-0.522616,3243.007632,-1.756862,12.024163,0
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340,-3.467680,-1.398706,3233.417139,-2.068974,1.177653,0
2010-01-11,3301.61,3306.75,3197.33,3212.75,1.363272e+10,2.924114e+09,4.662171,-3.400530,-1.941312,3229.885932,-1.459219,0.705286,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002,5.492395,-0.850851,3374.647089,6.343246,2.400873,0
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083,10.480643,1.415448,3376.183039,9.065195,1.429110,0
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220,12.829492,3.698257,3377.524103,9.131235,1.007285,0
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962,14.202869,5.799179,3378.811823,8.403690,0.920323,0
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588,13.491265,7.337596,3379.883945,6.153669,0.732258,0

In [84]:
data=data[~data['res'].isin([0])]
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,DIF-DEA,div_temp,res
date,,,,,,,,,,,,,
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,-0.146111,-0.381386,-1
2010-01-12,3205.70,3275.20,3180.08,3273.97,1.406552e+10,2.924114e+09,4.810183,-0.525524,-1.583014,3236.374154,1.057490,-0.724696,1
2010-01-13,3204.98,3232.82,3165.48,3172.66,1.583443e+10,2.924114e+09,5.415119,-3.407579,-2.021491,3228.128362,-1.386088,-1.310734,-1
2010-01-18,3213.64,3238.24,3202.21,3237.10,1.350672e+10,2.924114e+09,4.619082,-1.428417,-2.161868,3227.431390,0.733451,-3.109514,1
2010-01-20,3252.04,3255.13,3148.33,3151.85,1.582431e+10,2.924114e+09,5.411659,-4.327242,-2.255985,3222.833081,-2.071257,-1.226382,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-19,3427.55,3479.01,3414.36,3477.55,3.027358e+10,1.940575e+10,1.560031,-9.410908,-12.412435,3359.278557,3.001527,-3.060573,1
2021-05-07,3446.41,3457.89,3416.78,3418.87,3.537854e+10,1.940575e+10,1.823095,-3.341568,-2.162101,3369.235854,-1.179466,-1.051354,-1
2021-05-12,3429.75,3466.37,3428.39,3462.75,3.114445e+10,1.940575e+10,1.604908,-2.599568,-2.928421,3371.454626,0.328853,-0.229038,1
2021-05-13,3432.14,3448.02,3418.38,3429.54,3.193253e+10,1.940575e+10,1.645519,-3.772198,-3.097177,3372.032590,-0.675022,-2.052653,-1
2021-05-14,3436.09,3490.64,3422.56,3490.38,3.369823e+10,1.940575e+10,1.736507,0.205396,-2.436662,3373.210176,2.642058,-3.914034,1

In [85]:
data=data[~data.index.isin(['2010-01-06','2021-05-14'])]
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,DIF-DEA,div_temp,res
date,,,,,,,,,,,,,
2010-01-12,3205.70,3275.20,3180.08,3273.97,1.406552e+10,2.924114e+09,4.810183,-0.525524,-1.583014,3236.374154,1.057490,-0.724696,1
2010-01-13,3204.98,3232.82,3165.48,3172.66,1.583443e+10,2.924114e+09,5.415119,-3.407579,-2.021491,3228.128362,-1.386088,-1.310734,-1
2010-01-18,3213.64,3238.24,3202.21,3237.10,1.350672e+10,2.924114e+09,4.619082,-1.428417,-2.161868,3227.431390,0.733451,-3.109514,1
2010-01-20,3252.04,3255.13,3148.33,3151.85,1.582431e+10,2.924114e+09,5.411659,-4.327242,-2.255985,3222.833081,-2.071257,-1.226382,-1
2010-02-11,2985.08,3001.64,2976.08,2985.50,5.664630e+09,2.924114e+09,1.937212,-43.869029,-44.750627,3092.054717,0.881598,-0.383865,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-14,3397.02,3420.03,3392.98,3416.72,2.332423e+10,1.940575e+10,1.201924,-12.592971,-12.448865,3356.983176,-0.144106,-0.143316,-1
2021-04-19,3427.55,3479.01,3414.36,3477.55,3.027358e+10,1.940575e+10,1.560031,-9.410908,-12.412435,3359.278557,3.001527,-3.060573,1
2021-05-07,3446.41,3457.89,3416.78,3418.87,3.537854e+10,1.940575e+10,1.823095,-3.341568,-2.162101,3369.235854,-1.179466,-1.051354,-1
2021-05-12,3429.75,3466.37,3428.39,3462.75,3.114445e+10,1.940575e+10,1.604908,-2.599568,-2.928421,3371.454626,0.328853,-0.229038,1
2021-05-13,3432.14,3448.02,3418.38,3429.54,3.193253e+10,1.940575e+10,1.645519,-3.772198,-3.097177,3372.032590,-0.675022,-2.052653,-1

In [86]:
data['mutply']=data['open']

<ipython-input-86-656834c59151>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['mutply']=data['open']

In [87]:
data['mutply']=data.apply(lambda x:(1/x['mutply']) if(x['res']==1) else x['mutply'],axis=1)
data

<ipython-input-87-17c33738e89f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['mutply']=data.apply(lambda x:(1/x['mutply']) if(x['res']==1) else x['mutply'],axis=1)

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,DIF-DEA,div_temp,res,mutply
date,,,,,,,,,,,,,,
2010-01-12,3205.70,3275.20,3180.08,3273.97,1.406552e+10,2.924114e+09,4.810183,-0.525524,-1.583014,3236.374154,1.057490,-0.724696,1,0.000312
2010-01-13,3204.98,3232.82,3165.48,3172.66,1.583443e+10,2.924114e+09,5.415119,-3.407579,-2.021491,3228.128362,-1.386088,-1.310734,-1,3204.980000
2010-01-18,3213.64,3238.24,3202.21,3237.10,1.350672e+10,2.924114e+09,4.619082,-1.428417,-2.161868,3227.431390,0.733451,-3.109514,1,0.000311
2010-01-20,3252.04,3255.13,3148.33,3151.85,1.582431e+10,2.924114e+09,5.411659,-4.327242,-2.255985,3222.833081,-2.071257,-1.226382,-1,3252.040000
2010-02-11,2985.08,3001.64,2976.08,2985.50,5.664630e+09,2.924114e+09,1.937212,-43.869029,-44.750627,3092.054717,0.881598,-0.383865,1,0.000335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-14,3397.02,3420.03,3392.98,3416.72,2.332423e+10,1.940575e+10,1.201924,-12.592971,-12.448865,3356.983176,-0.144106,-0.143316,-1,3397.020000
2021-04-19,3427.55,3479.01,3414.36,3477.55,3.027358e+10,1.940575e+10,1.560031,-9.410908,-12.412435,3359.278557,3.001527,-3.060573,1,0.000292
2021-05-07,3446.41,3457.89,3416.78,3418.87,3.537854e+10,1.940575e+10,1.823095,-3.341568,-2.162101,3369.235854,-1.179466,-1.051354,-1,3446.410000
2021-05-12,3429.75,3466.37,3428.39,3462.75,3.114445e+10,1.940575e+10,1.604908,-2.599568,-2.928421,3371.454626,0.328853,-0.229038,1,0.000292
2021-05-13,3432.14,3448.02,3418.38,3429.54,3.193253e+10,1.940575e+10,1.645519,-3.772198,-3.097177,3372.032590,-0.675022,-2.052653,-1,3432.140000

In [88]:
return_final=data['mutply'].cumprod()

In [89]:
return_final

date
2010-01-12     0.000312
2010-01-13     0.999775
2010-01-18     0.000311
2010-01-20     1.011722
2010-02-11     0.000339
                ...
2021-04-14    10.782759
2021-04-19     0.003146
2021-05-07    10.842091
2021-05-12     0.003161
2021-05-13    10.849646
Name: mutply, Length: 206, dtype: float64

In [ ]:
## 最终收益为1