In [57]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [58]:
data=pd.read_csv('sh000001.csv',index_col='date')

In [59]:
data

,open,high,low,close,volume,outstanding_share,turnover
date,,,,,,,
2010-01-04,3289.75,3295.28,3243.32,3243.76,1.094479e+10,2.924114e+09,3.742943
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340
...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588

In [60]:
data['DIF']=data['close'].ewm(span=12).mean()-data['close'].ewm(span=26).mean()

In [61]:
data['DEA']=data['DIF'].ewm(span=9).mean()

In [62]:
data['EMA200']=data['close'].ewm(span=200).mean()

In [63]:
# 该列辅助判断当前是在EMA200以上还是以下
data['EMA200-close']=data['EMA200']-data['close']

In [64]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close
date,,,,,,,,,,,
2010-01-04,3289.75,3295.28,3243.32,3243.76,1.094479e+10,2.924114e+09,3.742943,0.000000,0.000000,3243.760000,0.000000
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932,0.861987,0.478882,3263.066050,-19.113950
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,5.867831
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719,-2.279478,-0.522616,3243.007632,50.227632
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340,-3.467680,-1.398706,3233.417139,37.417139
...,...,...,...,...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002,5.492395,-0.850851,3374.647089,-142.972911
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083,10.480643,1.415448,3376.183039,-152.826961
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220,12.829492,3.698257,3377.524103,-133.435897
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962,14.202869,5.799179,3378.811823,-128.128177
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588,13.491265,7.337596,3379.883945,-106.676055

## 结合EMA200复盘金叉买、死叉卖的收益结果

In [65]:
data['DIF-DEA']=data['DIF']-data['DEA']

In [66]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close,DIF-DEA
date,,,,,,,,,,,,
2010-01-04,3289.75,3295.28,3243.32,3243.76,1.094479e+10,2.924114e+09,3.742943,0.000000,0.000000,3243.760000,0.000000,0.000000
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932,0.861987,0.478882,3263.066050,-19.113950,0.383105
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,5.867831,-0.146111
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719,-2.279478,-0.522616,3243.007632,50.227632,-1.756862
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340,-3.467680,-1.398706,3233.417139,37.417139,-2.068974
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002,5.492395,-0.850851,3374.647089,-142.972911,6.343246
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083,10.480643,1.415448,3376.183039,-152.826961,9.065195
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220,12.829492,3.698257,3377.524103,-133.435897,9.131235
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962,14.202869,5.799179,3378.811823,-128.128177,8.403690
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588,13.491265,7.337596,3379.883945,-106.676055,6.153669

In [67]:
# data['div_temp']为判断金叉死叉辅助列
data['div_temp']=data['DIF-DEA']/data['DIF-DEA'].shift(1)

In [68]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close,DIF-DEA,div_temp
date,,,,,,,,,,,,,
2010-01-04,3289.75,3295.28,3243.32,3243.76,1.094479e+10,2.924114e+09,3.742943,0.000000,0.000000,3243.760000,0.000000,0.000000,NaN
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932,0.861987,0.478882,3263.066050,-19.113950,0.383105,inf
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,5.867831,-0.146111,-0.381386
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719,-2.279478,-0.522616,3243.007632,50.227632,-1.756862,12.024163
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340,-3.467680,-1.398706,3233.417139,37.417139,-2.068974,1.177653
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002,5.492395,-0.850851,3374.647089,-142.972911,6.343246,2.400873
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083,10.480643,1.415448,3376.183039,-152.826961,9.065195,1.429110
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220,12.829492,3.698257,3377.524103,-133.435897,9.131235,1.007285
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962,14.202869,5.799179,3378.811823,-128.128177,8.403690,0.920323
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588,13.491265,7.337596,3379.883945,-106.676055,6.153669,0.732258

In [69]:
data=data.dropna()

In [70]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close,DIF-DEA,div_temp
date,,,,,,,,,,,,,
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932,0.861987,0.478882,3263.066050,-19.113950,0.383105,inf
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,5.867831,-0.146111,-0.381386
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719,-2.279478,-0.522616,3243.007632,50.227632,-1.756862,12.024163
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340,-3.467680,-1.398706,3233.417139,37.417139,-2.068974,1.177653
2010-01-11,3301.61,3306.75,3197.33,3212.75,1.363272e+10,2.924114e+09,4.662171,-3.400530,-1.941312,3229.885932,17.135932,-1.459219,0.705286
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002,5.492395,-0.850851,3374.647089,-142.972911,6.343246,2.400873
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083,10.480643,1.415448,3376.183039,-152.826961,9.065195,1.429110
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220,12.829492,3.698257,3377.524103,-133.435897,9.131235,1.007285
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962,14.202869,5.799179,3378.811823,-128.128177,8.403690,0.920323
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588,13.491265,7.337596,3379.883945,-106.676055,6.153669,0.732258

In [71]:
data['res']=data.apply(lambda x: 0 if (x['div_temp'] >= 0) else (1 if (x['DIF-DEA'] > 0) else -1), axis=1)

<ipython-input-71-76ee0db85312>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['res']=data.apply(lambda x: 0 if (x['div_temp'] >= 0) else (1 if (x['DIF-DEA'] > 0) else -1), axis=1)

In [72]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close,DIF-DEA,div_temp,res
date,,,,,,,,,,,,,,
2010-01-05,3254.47,3290.51,3221.46,3282.18,1.261151e+10,2.924114e+09,4.312932,0.861987,0.478882,3263.066050,-19.113950,0.383105,inf,0
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,5.867831,-0.146111,-0.381386,-1
2010-01-07,3253.99,3268.82,3176.71,3192.78,1.286528e+10,2.924114e+09,4.399719,-2.279478,-0.522616,3243.007632,50.227632,-1.756862,12.024163,0
2010-01-08,3177.26,3198.92,3149.02,3196.00,9.837714e+09,2.924114e+09,3.364340,-3.467680,-1.398706,3233.417139,37.417139,-2.068974,1.177653,0
2010-01-11,3301.61,3306.75,3197.33,3212.75,1.363272e+10,2.924114e+09,4.662171,-3.400530,-1.941312,3229.885932,17.135932,-1.459219,0.705286,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-17,3490.41,3530.51,3490.14,3517.62,3.221360e+10,1.940575e+10,1.660002,5.492395,-0.850851,3374.647089,-142.972911,6.343246,2.400873,0
2021-05-18,3520.65,3529.01,3510.86,3529.01,2.713086e+10,1.940575e+10,1.398083,10.480643,1.415448,3376.183039,-152.826961,9.065195,1.429110,0
2021-05-19,3521.11,3521.11,3503.82,3510.96,2.783211e+10,1.940575e+10,1.434220,12.829492,3.698257,3377.524103,-133.435897,9.131235,1.007285,0
2021-05-20,3500.88,3517.74,3486.07,3506.94,3.260093e+10,1.940575e+10,1.679962,14.202869,5.799179,3378.811823,-128.128177,8.403690,0.920323,0
2021-05-21,3510.84,3518.38,3479.67,3486.56,2.838263e+10,1.940575e+10,1.462588,13.491265,7.337596,3379.883945,-106.676055,6.153669,0.732258,0

In [73]:
data=data[~data['res'].isin([0])]
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close,DIF-DEA,div_temp,res
date,,,,,,,,,,,,,,
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,5.867831,-0.146111,-0.381386,-1
2010-01-12,3205.70,3275.20,3180.08,3273.97,1.406552e+10,2.924114e+09,4.810183,-0.525524,-1.583014,3236.374154,-37.595846,1.057490,-0.724696,1
2010-01-13,3204.98,3232.82,3165.48,3172.66,1.583443e+10,2.924114e+09,5.415119,-3.407579,-2.021491,3228.128362,55.468362,-1.386088,-1.310734,-1
2010-01-18,3213.64,3238.24,3202.21,3237.10,1.350672e+10,2.924114e+09,4.619082,-1.428417,-2.161868,3227.431390,-9.668610,0.733451,-3.109514,1
2010-01-20,3252.04,3255.13,3148.33,3151.85,1.582431e+10,2.924114e+09,5.411659,-4.327242,-2.255985,3222.833081,70.983081,-2.071257,-1.226382,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-19,3427.55,3479.01,3414.36,3477.55,3.027358e+10,1.940575e+10,1.560031,-9.410908,-12.412435,3359.278557,-118.271443,3.001527,-3.060573,1
2021-05-07,3446.41,3457.89,3416.78,3418.87,3.537854e+10,1.940575e+10,1.823095,-3.341568,-2.162101,3369.235854,-49.634146,-1.179466,-1.051354,-1
2021-05-12,3429.75,3466.37,3428.39,3462.75,3.114445e+10,1.940575e+10,1.604908,-2.599568,-2.928421,3371.454626,-91.295374,0.328853,-0.229038,1
2021-05-13,3432.14,3448.02,3418.38,3429.54,3.193253e+10,1.940575e+10,1.645519,-3.772198,-3.097177,3372.032590,-57.507410,-0.675022,-2.052653,-1
2021-05-14,3436.09,3490.64,3422.56,3490.38,3.369823e+10,1.940575e+10,1.736507,0.205396,-2.436662,3373.210176,-117.169824,2.642058,-3.914034,1

In [74]:
data['EMA200-close']=data.apply(lambda x:(1) if(x['EMA200-close']>0) else -1,axis=1)

<ipython-input-74-fd465099feb0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['EMA200-close']=data.apply(lambda x:(1) if(x['EMA200-close']>0) else -1,axis=1)

In [75]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close,DIF-DEA,div_temp,res
date,,,,,,,,,,,,,,
2010-01-06,3277.52,3295.87,3253.04,3254.22,1.236514e+10,2.924114e+09,4.228678,0.231305,0.377416,3260.087831,1,-0.146111,-0.381386,-1
2010-01-12,3205.70,3275.20,3180.08,3273.97,1.406552e+10,2.924114e+09,4.810183,-0.525524,-1.583014,3236.374154,-1,1.057490,-0.724696,1
2010-01-13,3204.98,3232.82,3165.48,3172.66,1.583443e+10,2.924114e+09,5.415119,-3.407579,-2.021491,3228.128362,1,-1.386088,-1.310734,-1
2010-01-18,3213.64,3238.24,3202.21,3237.10,1.350672e+10,2.924114e+09,4.619082,-1.428417,-2.161868,3227.431390,-1,0.733451,-3.109514,1
2010-01-20,3252.04,3255.13,3148.33,3151.85,1.582431e+10,2.924114e+09,5.411659,-4.327242,-2.255985,3222.833081,1,-2.071257,-1.226382,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-19,3427.55,3479.01,3414.36,3477.55,3.027358e+10,1.940575e+10,1.560031,-9.410908,-12.412435,3359.278557,-1,3.001527,-3.060573,1
2021-05-07,3446.41,3457.89,3416.78,3418.87,3.537854e+10,1.940575e+10,1.823095,-3.341568,-2.162101,3369.235854,-1,-1.179466,-1.051354,-1
2021-05-12,3429.75,3466.37,3428.39,3462.75,3.114445e+10,1.940575e+10,1.604908,-2.599568,-2.928421,3371.454626,-1,0.328853,-0.229038,1
2021-05-13,3432.14,3448.02,3418.38,3429.54,3.193253e+10,1.940575e+10,1.645519,-3.772198,-3.097177,3372.032590,-1,-0.675022,-2.052653,-1
2021-05-14,3436.09,3490.64,3422.56,3490.38,3.369823e+10,1.940575e+10,1.736507,0.205396,-2.436662,3373.210176,-1,2.642058,-3.914034,1

In [76]:
data=data[data['EMA200-close']==data['res']]
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close,DIF-DEA,div_temp,res
date,,,,,,,,,,,,,,
2010-02-11,2985.08,3001.64,2976.08,2985.50,5.664630e+09,2.924114e+09,1.937212,-43.869029,-44.750627,3092.054717,1,0.881598,-0.383865,1
2010-03-18,3053.16,3063.59,3035.02,3046.09,9.137912e+09,2.924114e+09,3.125019,-4.164430,-4.965492,3066.593534,1,0.801062,-1.081091,1
2010-05-25,2654.36,2659.74,2609.09,2622.63,9.326905e+09,2.924114e+09,3.189651,-101.245913,-104.775397,2966.086921,1,3.529484,-8.072127,1
2010-07-09,2416.58,2485.60,2398.68,2470.92,8.589014e+09,3.105368e+09,2.765861,-58.447999,-62.310710,2802.546166,1,3.862711,-1.746678,1
2010-08-17,2663.18,2677.57,2654.01,2671.89,1.226383e+10,3.105368e+09,3.949236,28.690020,27.948453,2736.207420,1,0.741567,-0.488187,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-26,3610.97,3610.97,3564.74,3569.43,2.781399e+10,1.940575e+10,1.433286,47.475457,49.519370,3275.617202,-1,-2.043914,-0.980310,-1
2021-02-25,3595.54,3608.56,3568.47,3585.05,3.662323e+10,1.940575e+10,1.887236,26.861650,27.953126,3322.126790,-1,-1.091476,-0.514372,-1
2021-04-14,3397.02,3420.03,3392.98,3416.72,2.332423e+10,1.940575e+10,1.201924,-12.592971,-12.448865,3356.983176,-1,-0.144106,-0.143316,-1
2021-05-07,3446.41,3457.89,3416.78,3418.87,3.537854e+10,1.940575e+10,1.823095,-3.341568,-2.162101,3369.235854,-1,-1.179466,-1.051354,-1
2021-05-13,3432.14,3448.02,3418.38,3429.54,3.193253e+10,1.940575e+10,1.645519,-3.772198,-3.097177,3372.032590,-1,-0.675022,-2.052653,-1

In [77]:
data['res']=data['res']*data['res'].shift(1)

<ipython-input-77-a99aa3c47d9e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['res']=data['res']*data['res'].shift(1)

In [78]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close,DIF-DEA,div_temp,res
date,,,,,,,,,,,,,,
2010-02-11,2985.08,3001.64,2976.08,2985.50,5.664630e+09,2.924114e+09,1.937212,-43.869029,-44.750627,3092.054717,1,0.881598,-0.383865,NaN
2010-03-18,3053.16,3063.59,3035.02,3046.09,9.137912e+09,2.924114e+09,3.125019,-4.164430,-4.965492,3066.593534,1,0.801062,-1.081091,1.0
2010-05-25,2654.36,2659.74,2609.09,2622.63,9.326905e+09,2.924114e+09,3.189651,-101.245913,-104.775397,2966.086921,1,3.529484,-8.072127,1.0
2010-07-09,2416.58,2485.60,2398.68,2470.92,8.589014e+09,3.105368e+09,2.765861,-58.447999,-62.310710,2802.546166,1,3.862711,-1.746678,1.0
2010-08-17,2663.18,2677.57,2654.01,2671.89,1.226383e+10,3.105368e+09,3.949236,28.690020,27.948453,2736.207420,1,0.741567,-0.488187,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-26,3610.97,3610.97,3564.74,3569.43,2.781399e+10,1.940575e+10,1.433286,47.475457,49.519370,3275.617202,-1,-2.043914,-0.980310,1.0
2021-02-25,3595.54,3608.56,3568.47,3585.05,3.662323e+10,1.940575e+10,1.887236,26.861650,27.953126,3322.126790,-1,-1.091476,-0.514372,1.0
2021-04-14,3397.02,3420.03,3392.98,3416.72,2.332423e+10,1.940575e+10,1.201924,-12.592971,-12.448865,3356.983176,-1,-0.144106,-0.143316,1.0
2021-05-07,3446.41,3457.89,3416.78,3418.87,3.537854e+10,1.940575e+10,1.823095,-3.341568,-2.162101,3369.235854,-1,-1.179466,-1.051354,1.0
2021-05-13,3432.14,3448.02,3418.38,3429.54,3.193253e+10,1.940575e+10,1.645519,-3.772198,-3.097177,3372.032590,-1,-0.675022,-2.052653,1.0

In [79]:
data=data[~data['res'].isin([1])]

In [80]:
data

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close,DIF-DEA,div_temp,res
date,,,,,,,,,,,,,,
2010-02-11,2985.08,3001.64,2976.08,2985.50,5.664630e+09,2.924114e+09,1.937212,-43.869029,-44.750627,3092.054717,1,0.881598,-0.383865,NaN
2010-11-03,3044.02,3069.07,3017.10,3030.99,1.898480e+10,3.105368e+09,6.113545,87.286830,88.544253,2758.898565,-1,-1.257424,-0.910197,-1.0
2011-01-28,2741.31,2759.44,2733.29,2752.75,8.542799e+09,3.105359e+09,2.750986,-32.510227,-34.317361,2799.583949,1,1.807134,-0.973924,-1.0
2011-03-14,2923.98,2939.65,2914.46,2937.63,1.169106e+10,3.105359e+09,3.764803,35.847421,36.265175,2824.599755,-1,-0.417754,-0.168060,-1.0
2011-06-08,2742.04,2754.12,2715.25,2750.29,7.429466e+09,3.105359e+09,2.392467,-47.637666,-49.521750,2852.186781,1,1.884084,-1.803701,-1.0
2013-01-18,2295.81,2324.51,2285.97,2317.07,1.254380e+10,3.105358e+09,4.039406,53.504601,53.748604,2196.031730,-1,-0.244004,-3.376357,-1.0
2013-05-03,2179.05,2222.81,2179.05,2205.50,8.858346e+09,3.105358e+09,2.852601,-21.499243,-22.808458,2237.646796,1,1.309214,-5.520873,-1.0
2013-06-04,2297.10,2297.10,2264.76,2272.42,1.018958e+10,3.105358e+09,3.281290,16.630112,16.648180,2245.010855,-1,-0.018068,-0.005721,-1.0
2013-07-09,1953.60,1969.15,1946.37,1965.45,6.453873e+09,4.968574e+09,1.298939,-64.696737,-65.216916,2207.964534,1,0.520179,-1.395453,-1.0
2013-09-25,2206.22,2217.97,2193.72,2198.52,1.602128e+10,4.968574e+09,3.224522,34.705866,36.714903,2164.329896,-1,-2.009037,-27.661474,-1.0
2014-01-22,2009.97,2052.34,2008.93,2051.75,9.889286e+09,5.575902e+09,1.773576,-33.240733,-35.868082,2147.148770,1,2.627349,-1.847873,-1.0
2014-08-15,2207.23,2230.87,2203.24,2226.73,1.499787e+10,6.691059e+09,2.241479,38.150243,38.302480,2098.350965,-1,-0.152237,-0.534528,-1.0
2015-09-10,3190.55,3243.28,3178.90,3197.89,2.732618e+10,1.180405e+10,2.314982,-181.685863,-189.463159,3613.845407,1,7.777296,-63.049701,-1.0
2015-11-23,3630.87,3654.75,3598.87,3610.32,3.159975e+10,1.180405e+10,2.677025,74.781377,76.740027,3523.632631,-1,-1.958649,-2.860725,-1.0
2016-02-04,2751.43,2793.30,2751.31,2781.02,1.703820e+10,1.180405e+10,1.443419,-158.390124,-165.169623,3402.008409,1,6.779499,-4.997542,-1.0
2016-12-02,3270.12,3279.71,3235.28,3243.84,2.595672e+10,1.463118e+10,1.774069,39.784516,40.479159,3099.088147,-1,-0.694642,-0.328097,-1.0
2017-05-16,3082.87,3113.51,3060.53,3112.96,1.737756e+10,1.691799e+10,1.027164,-35.662335,-35.671353,3154.610237,1,0.009018,-0.002467,-1.0
2017-07-17,3219.79,3230.35,3139.50,3176.46,2.662053e+10,1.691799e+10,1.573504,17.009620,18.812206,3154.589579,-1,-1.802586,-1.384269,-1.0
2018-03-06,3266.49,3290.25,3243.65,3289.64,1.953580e+10,1.691798e+10,1.154736,-36.495744,-39.256645,3309.977491,1,2.760902,-7.222267,-1.0
2019-03-14,3013.60,3041.16,2968.82,2990.68,3.731418e+10,1.717025e+10,2.173188,96.290103,102.625542,2792.013762,-1,-6.335439,-215.158439,-1.0
2019-08-19,2835.52,2883.10,2829.85,2883.10,2.145467e+10,1.717091e+10,1.249478,-28.147090,-32.718696,2897.061944,1,4.571606,-3.272539,-1.0
2019-09-23,2998.40,2998.40,2960.83,2977.08,1.681394e+10,1.940575e+10,0.866441,29.433991,30.976037,2909.413389,-1,-1.542046,-1.119674,-1.0
2019-12-06,2902.28,2912.01,2894.75,2912.01,1.341289e+10,1.940575e+10,0.691181,-13.291152,-15.055430,2917.498956,1,1.764278,-5.116015,-1.0
2020-01-16,3095.73,3096.37,3070.88,3074.08,2.033755e+10,1.940575e+10,1.048016,36.552652,37.673831,2944.988209,-1,-1.121179,-0.624374,-1.0
2020-04-02,2720.23,2780.64,2719.90,2780.64,2.178646e+10,1.940575e+10,1.122680,-52.815269,-56.166646,2923.373916,1,3.351378,-3.649076,-1.0
2020-07-17,3214.40,3252.78,3181.28,3214.13,3.596524e+10,1.940575e+10,1.853329,103.224172,109.143518,2954.363382,-1,-5.919346,-0.886756,-1.0

In [81]:
data['mutply']=data['open']

<ipython-input-81-656834c59151>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['mutply']=data['open']

In [82]:
data['mutply']=data.apply(lambda x:(1/x['mutply']) if(x['EMA200-close']==1) else x['mutply'],axis=1)
data

<ipython-input-82-387e839ae403>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['mutply']=data.apply(lambda x:(1/x['mutply']) if(x['EMA200-close']==1) else x['mutply'],axis=1)

,open,high,low,close,volume,outstanding_share,turnover,DIF,DEA,EMA200,EMA200-close,DIF-DEA,div_temp,res,mutply
date,,,,,,,,,,,,,,,
2010-02-11,2985.08,3001.64,2976.08,2985.50,5.664630e+09,2.924114e+09,1.937212,-43.869029,-44.750627,3092.054717,1,0.881598,-0.383865,NaN,0.000335
2010-11-03,3044.02,3069.07,3017.10,3030.99,1.898480e+10,3.105368e+09,6.113545,87.286830,88.544253,2758.898565,-1,-1.257424,-0.910197,-1.0,3044.020000
2011-01-28,2741.31,2759.44,2733.29,2752.75,8.542799e+09,3.105359e+09,2.750986,-32.510227,-34.317361,2799.583949,1,1.807134,-0.973924,-1.0,0.000365
2011-03-14,2923.98,2939.65,2914.46,2937.63,1.169106e+10,3.105359e+09,3.764803,35.847421,36.265175,2824.599755,-1,-0.417754,-0.168060,-1.0,2923.980000
2011-06-08,2742.04,2754.12,2715.25,2750.29,7.429466e+09,3.105359e+09,2.392467,-47.637666,-49.521750,2852.186781,1,1.884084,-1.803701,-1.0,0.000365
2013-01-18,2295.81,2324.51,2285.97,2317.07,1.254380e+10,3.105358e+09,4.039406,53.504601,53.748604,2196.031730,-1,-0.244004,-3.376357,-1.0,2295.810000
2013-05-03,2179.05,2222.81,2179.05,2205.50,8.858346e+09,3.105358e+09,2.852601,-21.499243,-22.808458,2237.646796,1,1.309214,-5.520873,-1.0,0.000459
2013-06-04,2297.10,2297.10,2264.76,2272.42,1.018958e+10,3.105358e+09,3.281290,16.630112,16.648180,2245.010855,-1,-0.018068,-0.005721,-1.0,2297.100000
2013-07-09,1953.60,1969.15,1946.37,1965.45,6.453873e+09,4.968574e+09,1.298939,-64.696737,-65.216916,2207.964534,1,0.520179,-1.395453,-1.0,0.000512
2013-09-25,2206.22,2217.97,2193.72,2198.52,1.602128e+10,4.968574e+09,3.224522,34.705866,36.714903,2164.329896,-1,-2.009037,-27.661474,-1.0,2206.220000
2014-01-22,2009.97,2052.34,2008.93,2051.75,9.889286e+09,5.575902e+09,1.773576,-33.240733,-35.868082,2147.148770,1,2.627349,-1.847873,-1.0,0.000498
2014-08-15,2207.23,2230.87,2203.24,2226.73,1.499787e+10,6.691059e+09,2.241479,38.150243,38.302480,2098.350965,-1,-0.152237,-0.534528,-1.0,2207.230000
2015-09-10,3190.55,3243.28,3178.90,3197.89,2.732618e+10,1.180405e+10,2.314982,-181.685863,-189.463159,3613.845407,1,7.777296,-63.049701,-1.0,0.000313
2015-11-23,3630.87,3654.75,3598.87,3610.32,3.159975e+10,1.180405e+10,2.677025,74.781377,76.740027,3523.632631,-1,-1.958649,-2.860725,-1.0,3630.870000
2016-02-04,2751.43,2793.30,2751.31,2781.02,1.703820e+10,1.180405e+10,1.443419,-158.390124,-165.169623,3402.008409,1,6.779499,-4.997542,-1.0,0.000363
2016-12-02,3270.12,3279.71,3235.28,3243.84,2.595672e+10,1.463118e+10,1.774069,39.784516,40.479159,3099.088147,-1,-0.694642,-0.328097,-1.0,3270.120000
2017-05-16,3082.87,3113.51,3060.53,3112.96,1.737756e+10,1.691799e+10,1.027164,-35.662335,-35.671353,3154.610237,1,0.009018,-0.002467,-1.0,0.000324
2017-07-17,3219.79,3230.35,3139.50,3176.46,2.662053e+10,1.691799e+10,1.573504,17.009620,18.812206,3154.589579,-1,-1.802586,-1.384269,-1.0,3219.790000
2018-03-06,3266.49,3290.25,3243.65,3289.64,1.953580e+10,1.691798e+10,1.154736,-36.495744,-39.256645,3309.977491,1,2.760902,-7.222267,-1.0,0.000306
2019-03-14,3013.60,3041.16,2968.82,2990.68,3.731418e+10,1.717025e+10,2.173188,96.290103,102.625542,2792.013762,-1,-6.335439,-215.158439,-1.0,3013.600000
2019-08-19,2835.52,2883.10,2829.85,2883.10,2.145467e+10,1.717091e+10,1.249478,-28.147090,-32.718696,2897.061944,1,4.571606,-3.272539,-1.0,0.000353
2019-09-23,2998.40,2998.40,2960.83,2977.08,1.681394e+10,1.940575e+10,0.866441,29.433991,30.976037,2909.413389,-1,-1.542046,-1.119674,-1.0,2998.400000
2019-12-06,2902.28,2912.01,2894.75,2912.01,1.341289e+10,1.940575e+10,0.691181,-13.291152,-15.055430,2917.498956,1,1.764278,-5.116015,-1.0,0.000345
2020-01-16,3095.73,3096.37,3070.88,3074.08,2.033755e+10,1.940575e+10,1.048016,36.552652,37.673831,2944.988209,-1,-1.121179,-0.624374,-1.0,3095.730000
2020-04-02,2720.23,2780.64,2719.90,2780.64,2.178646e+10,1.940575e+10,1.122680,-52.815269,-56.166646,2923.373916,1,3.351378,-3.649076,-1.0,0.000368
2020-07-17,3214.40,3252.78,3181.28,3214.13,3.596524e+10,1.940575e+10,1.853329,103.224172,109.143518,2954.363382,-1,-5.919346,-0.886756,-1.0,3214.400000

In [83]:
return_final=data['mutply'].cumprod()

In [84]:
return_final

date
2010-02-11    0.000335
2010-11-03    1.019745
2011-01-28    0.000372
2011-03-14    1.087697
2011-06-08    0.000397
2013-01-18    0.910689
2013-05-03    0.000418
2013-06-04    0.960025
2013-07-09    0.000491
2013-09-25    1.084166
2014-01-22    0.000539
2014-08-15    1.190567
2015-09-10    0.000373
2015-11-23    1.354874
2016-02-04    0.000492
2016-12-02    1.610290
2017-05-16    0.000522
2017-07-17    1.681808
2018-03-06    0.000515
2019-03-14    1.551604
2019-08-19    0.000547
2019-09-23    1.640732
2019-12-06    0.000565
2020-01-16    1.750094
2020-04-02    0.000643
2020-07-17    2.068025
Name: mutply, dtype: float64